before_script:
  - mkdir -p /usr/src/vmlcm
  - cp -r ./* /usr/src/vmlcm
  - cd /usr/src/vmlcm
  - go get -d -v ./...
  - go install -v

tests:
  type: test
  script:
    - go test
  tags:
    - golang
    - plain
