before_script:
  - mkdir -p /workspace/src/vmlcm
  - cp -r ./* /workspace/src/vmlcm
  - cd /workspace/src/vmlcm
  - export GOPATH=/workspace
  - go get -v ./...
  - go install -v

tests:
  type: test
  script:
    - go test
  tags:
    - golang
    - plain
